export const CONNECT_SIGNER_AND_PROVIDER = "CONNECT_SIGNER_AND_PROVIDER";

export const INITIALIZE_WEBTHREE_MODAL = "INITIALIZE_WEBTHREE_MODAL";
export const SET_CONTRACT_LOADING = "SET_CONTRACT_LOADING";
export const INITIALIZE_CONTRACT = "INITIALIZE_CONTRACT";
export const CONTRACT_SUCCESS = "CONTRACT_SUCCESS";
export const CONTRACT_ERROR = "CONTRACT_ERROR";

export const SET_DATA_LOADING = "SET_DATA_LOADING";
export const GET_DATA = "GET_DATA";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_ERROR = "DATA_ERROR";

export const BUY = "BUY";
export const BUY_SUCCESS = "BUY_SUCCESS";
export const BUY_ERROR = "BUY_ERROR";

export const SELL = "SELL";
export const SELL_SUCCESS = "SELL_SUCCESS";
export const SELL_ERROR = "SELL_ERROR";

export const RESET_DAPP = "RESET_DAPP";
